/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ARangePicker: typeof import('@arco-design/web-vue')['RangePicker']
    Arco: typeof import('./src/components/Arco.vue')['default']
    Child: typeof import('./src/components/Child.vue')['default']
    EasyMarkdownEditor: typeof import('./src/components/EasyMarkdownEditor.vue')['default']
    GridLayout: typeof import('./src/components/GridLayout.vue')['default']
    HtmlCanvas: typeof import('./src/components/HtmlCanvas.vue')['default']
    Monaco: typeof import('./src/components/Monaco.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SortTable: typeof import('./src/components/SortTable.vue')['default']
    TestComponent: typeof import('./src/components/TestComponent.vue')['default']
  }
}
